// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAASg_YP3qXz14graNFHQ1QclB18O9dA2Y',
    appId: '1:110781656441:web:b34f92bbd7d926ccc553a8',
    messagingSenderId: '110781656441',
    projectId: 'final-6448d',
    authDomain: 'final-6448d.firebaseapp.com',
    storageBucket: 'final-6448d.firebasestorage.app',
    measurementId: 'G-N107PLCRCW',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYNcooQ72HbnOnhu0q57Y-uU1VmK_tWq0',
    appId: '1:110781656441:ios:4fa67e0562b6d92fc553a8',
    messagingSenderId: '110781656441',
    projectId: 'final-6448d',
    storageBucket: 'final-6448d.firebasestorage.app',
    iosBundleId: 'com.example.cosmeticShop',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZaoHQj6sZ7scC2HYQTwFTty_KApMjSLo',
    appId: '1:110781656441:android:93455f205a5bbc5bc553a8',
    messagingSenderId: '110781656441',
    projectId: 'final-6448d',
    storageBucket: 'final-6448d.firebasestorage.app',
  );

}